var Reviews = [
 {
   "Landsting": "Stockholm",
   "Municipality": "Lidingö",
   "ENSEMBLE": "86",
   "Emotional_support": "84",
   "Participation": "86",
   "Respect": "89",
   "Coordination": "84",
   "Knowledge": "81",
   "Availability": "86"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Nynäshamn",
   "ENSEMBLE": "78",
   "Emotional_support": "73",
   "Participation": "75",
   "Respect": "82",
   "Coordination": "70",
   "Knowledge": "72",
   "Availability": "80"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Botkyrka",
   "ENSEMBLE": "72",
   "Emotional_support": "69",
   "Participation": "76",
   "Respect": "77",
   "Coordination": "68",
   "Knowledge": "70",
   "Availability": "76"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Nykvarn",
   "ENSEMBLE": "86",
   "Emotional_support": "81",
   "Participation": "83",
   "Respect": "87",
   "Coordination": "82",
   "Knowledge": "79",
   "Availability": "89"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Sollentuna",
   "ENSEMBLE": "81",
   "Emotional_support": "77",
   "Participation": "83",
   "Respect": "85",
   "Coordination": "79",
   "Knowledge": "77",
   "Availability": "82"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Sigtuna",
   "ENSEMBLE": "80",
   "Emotional_support": "78",
   "Participation": "81",
   "Respect": "84",
   "Coordination": "73",
   "Knowledge": "77",
   "Availability": "84"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Vaxholm",
   "ENSEMBLE": "54",
   "Emotional_support": "53",
   "Participation": "56",
   "Respect": "66",
   "Coordination": "45",
   "Knowledge": "56",
   "Availability": "66"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Södertälje",
   "ENSEMBLE": "80",
   "Emotional_support": "77",
   "Participation": "80",
   "Respect": "85",
   "Coordination": "74",
   "Knowledge": "76",
   "Availability": "82"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Solna",
   "ENSEMBLE": "77",
   "Emotional_support": "72",
   "Participation": "77",
   "Respect": "82",
   "Coordination": "70",
   "Knowledge": "72",
   "Availability": "82"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Haninge",
   "ENSEMBLE": "73",
   "Emotional_support": "67",
   "Participation": "74",
   "Respect": "77",
   "Coordination": "67",
   "Knowledge": "68",
   "Availability": "76"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Huddinge",
   "ENSEMBLE": "74",
   "Emotional_support": "71",
   "Participation": "77",
   "Respect": "79",
   "Coordination": "68",
   "Knowledge": "70",
   "Availability": "77"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Upplands Väsby",
   "ENSEMBLE": "83",
   "Emotional_support": "80",
   "Participation": "82",
   "Respect": "85",
   "Coordination": "79",
   "Knowledge": "77",
   "Availability": "83"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Tyresö",
   "ENSEMBLE": "71",
   "Emotional_support": "68",
   "Participation": "74",
   "Respect": "79",
   "Coordination": "64",
   "Knowledge": "71",
   "Availability": "72"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Vallentuna",
   "ENSEMBLE": "70",
   "Emotional_support": "65",
   "Participation": "73",
   "Respect": "79",
   "Coordination": "61",
   "Knowledge": "70",
   "Availability": "75"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Salem",
   "ENSEMBLE": "75",
   "Emotional_support": "73",
   "Participation": "78",
   "Respect": "81",
   "Coordination": "62",
   "Knowledge": "71",
   "Availability": "78"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Stockholm",
   "ENSEMBLE": "80",
   "Emotional_support": "76",
   "Participation": "80",
   "Respect": "83",
   "Coordination": "75",
   "Knowledge": "76",
   "Availability": "81"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Upplands-Bro",
   "ENSEMBLE": "62",
   "Emotional_support": "53",
   "Participation": "62",
   "Respect": "70",
   "Coordination": "53",
   "Knowledge": "58",
   "Availability": "69"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Österåker",
   "ENSEMBLE": "83",
   "Emotional_support": "77",
   "Participation": "81",
   "Respect": "85",
   "Coordination": "80",
   "Knowledge": "76",
   "Availability": "84"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Ekerö",
   "ENSEMBLE": "82",
   "Emotional_support": "77",
   "Participation": "80",
   "Respect": "86",
   "Coordination": "73",
   "Knowledge": "78",
   "Availability": "86"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Värmdö",
   "ENSEMBLE": "89",
   "Emotional_support": "83",
   "Participation": "87",
   "Respect": "90",
   "Coordination": "80",
   "Knowledge": "81",
   "Availability": "86"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Norrtälje",
   "ENSEMBLE": "85",
   "Emotional_support": "79",
   "Participation": "82",
   "Respect": "88",
   "Coordination": "74",
   "Knowledge": "79",
   "Availability": "86"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Täby",
   "ENSEMBLE": "85",
   "Emotional_support": "83",
   "Participation": "86",
   "Respect": "90",
   "Coordination": "80",
   "Knowledge": "81",
   "Availability": "84"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Järfälla",
   "ENSEMBLE": "76",
   "Emotional_support": "74",
   "Participation": "75",
   "Respect": "82",
   "Coordination": "70",
   "Knowledge": "72",
   "Availability": "80"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Nacka",
   "ENSEMBLE": "82",
   "Emotional_support": "78",
   "Participation": "83",
   "Respect": "85",
   "Coordination": "77",
   "Knowledge": "79",
   "Availability": "83"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Danderyd",
   "ENSEMBLE": "86",
   "Emotional_support": "83",
   "Participation": "83",
   "Respect": "88",
   "Coordination": "79",
   "Knowledge": "81",
   "Availability": "87"
 },
 {
   "Landsting": "Stockholm",
   "Municipality": "Sundbyberg",
   "ENSEMBLE": "65",
   "Emotional_support": "62",
   "Participation": "70",
   "Respect": "73",
   "Coordination": "59",
   "Knowledge": "65",
   "Availability": "73"
 }
]